# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['role__sort_order']},
        ),
        migrations.RenameField('project', 'is_active', 'highlight'),
        migrations.AlterField(
            model_name='project',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Include in randomized project display on the home page.'),
        ),
    ]
