# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 21:16
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumb',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
