# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='users',
            field=models.ManyToManyField(related_name='blogposts', to=settings.AUTH_USER_MODEL, verbose_name='Authors'),
        ),
    ]
