# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklandingpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
