# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktemplate', '0003_auto_20161004_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklandingpage',
            options={'ordering': ('_order',), 'verbose_name': 'Generic Page', 'verbose_name_plural': 'Generic Pages'},
        ),
    ]
