# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_initial_types_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(help_text='Guest lecturer(s) or Workshop leader(s)', to=settings.AUTH_USER_MODEL),
        ),
    ]
