# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocktemplate', '0004_auto_20161010_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', mezzanine.core.fields.FileField(max_length=255, verbose_name='Image, Document')),
                ('generic_template', models.ManyToManyField(to='stocktemplate.StockLandingPage')),
            ],
        ),
    ]
