# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileattach', '0002_auto_20161020_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileattachment',
            old_name='image',
            new_name='attached_file',
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='display_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
