# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffprofiles', '0002_auto_20160923_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffer',
            name='full_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
