# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffprofiles', '0003_staffer_full_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staffer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='staffer',
            name='specialties',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
