# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffprofiles', '0004_auto_20161003_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffer',
            name='specialties',
        ),
        migrations.AddField(
            model_name='staffer',
            name='education',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='staff_member',
            field=models.ManyToManyField(to='staffprofiles.Staffer'),
        ),
    ]
