# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 22:33
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staffprofiles', '0006_auto_20161004_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffer',
            name='photo',
            field=mezzanine.core.fields.FileField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='profile_photo',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True),
        ),
    ]
