# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-30 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffprofiles', '0007_auto_20161004_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafflandingpage',
            options={'ordering': ('_order',), 'verbose_name': 'Staff List'},
        ),
    ]
