# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffprofiles', '0008_add_verbose_model_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafferpage',
            name='title',
            field=models.CharField(default='CDH @ Princeton Staff', max_length=500),
        ),
    ]
