# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffprofiles', '0009_add_default_for_unused_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafferpage',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
