# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 14:14
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify

#: initial set of tags that will be preloaded
INITIAL_TAGSSET = ["network analysis", "data visualization", "data modeling",
    "project management", "design", "mapping", "text analysis",
    "annotation", "archives", "rare books", "manuscripts", "history",
    "english", "slavic", "classics", "periodical studies", "literary studies"]

#: initial resource types, in sort order
INITIAL_RESOURCE_TYPES = ["website", "twitter", "github"]


def create_initial_tags(apps, schema_editor):
    Tag = apps.get_model("taggit", "Tag")
    Tag.objects.bulk_create([Tag(name=tag, slug=slugify(tag))
                             for tag in INITIAL_TAGSSET])

def remove_initial_tags(apps, schema_editor):
    Tag = apps.get_model("taggit", "Tag")
    Tag.objects.filter(name__in=INITIAL_TAGSSET).delete()


def create_initial_resource_types(apps, schema_editor):
    ResourceType = apps.get_model("resources", "ResourceType")
    ResourceType.objects.bulk_create([
        ResourceType(name=rtype, sort_order=idx)
        for idx, rtype in enumerate(INITIAL_RESOURCE_TYPES)
    ])

def remove_initial_resource_types(apps, schema_editor):
    ResourceType = apps.get_model("resources", "ResourceType")
    ResourceType.objects.filter(name__in=INITIAL_RESOURCE_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_tags,
            reverse_code=remove_initial_tags),
        migrations.RunPython(create_initial_resource_types,
            reverse_code=remove_initial_resource_types),
    ]
