# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('file', mezzanine.core.fields.FileField(blank=True, max_length=255, verbose_name='Image, Document')),
                ('url', models.URLField(blank=True)),
                ('attachment_type', models.CharField(choices=[('PDF', 'PDF Document'), ('DOC', 'MS Word Document'), ('VIDEO', 'Video'), ('URL', 'URL')], max_length=255)),
            ],
        ),
    ]
