# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 21:28
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'initial-tags', app_label='resources')


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_add_landing_page'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]