# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='override_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
