# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpages', '0002_auto_20160921_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_subtitle',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
