# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-30 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpages', '0005_auto_20161004_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ('-project_role__rank',), 'verbose_name': 'Project Member'},
        ),
    ]
