# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpages', '0007_project_app_remaining_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='title',
            field=models.CharField(default='CDH @ Princeton Projects', max_length=500),
        ),
    ]
