# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-30 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventspages', '0002_auto_20161004_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventslandingpage',
            options={'ordering': ('_order',), 'verbose_name': 'Event List'},
        ),
    ]
